POST http://localhost:8000/signup
Content-Type: application/json

{
    "username":"ramanshu",
    "password":"2838291"
}

###
POST http://localhost:8000/login
Content-Type:application/json

{
    "username":"himanshu",
    "password":"1231352"
}

###
POST http://localhost:8000/accounts
Content-Type:application/json

{
    "token":"5275be549cba7b17c59c0cd15186bc04ae6d4e12a66634ed2a82bea2ce0b05e1"
}

###
POST http://localhost:8000/transfer
Content-Type:application/json

{
    "token": "5275be549cba7b17c59c0cd15186bc04ae6d4e12a66634ed2a82bea2ce0b05e1",
    "transferFrom":"0082660240",
    "transferTo":"1514269930",
    "amount":"1000"
}

###
POST http://localhost:8000/transactionHistory
Content-Type:application/json

{
    "token":"5275be549cba7b17c59c0cd15186bc04ae6d4e12a66634ed2a82bea2ce0b05e1",
    "account":"0082660240"
}