POST http://localhost:8000/signup
Content-Type: application/json

{
    "username":"bravvohimu",
    "password":"1234"
}

###
POST http://localhost:8000/login
Content-Type:application/json

{
    "username":"bravohimu",
    "password":"1234"
}

###
POST http://localhost:8000/accounts
Content-Type:application/json

{
    "token":"706d9adf361d414fc6fda6529c4e7ce2c12419134fa3343818ae555aab40a57f"
}

###
POST http://localhost:8000/transfer
Content-Type:application/json

{
    "token":"706d9adf361d414fc6fda6529c4e7ce2c12419134fa3343818ae555aab40a57f",
    "transferFrom":"8566798871",
    "transferTo":"8407830464",
    "amount":"999"
}

###
POST http://localhost:8000/transactionHistory
Content-Type:application/json

{
    "token":"78a0f3bbb3226e7c7a71e0dc277ced2c09c7a24b22c5fdaf1bd061142cf09b84",
    "account":"0164484483"
}